version: '3.8'

services:
  nightout-postgres:
    image: postgres:14
    container_name: nightout-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nightout-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nightout-backend:
    image: zachholt/nightout-backend:latest
    container_name: nightout-backend
    depends_on:
      nightout-postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nightout-postgres:5432/nightoutdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: never
    ports:
      - "8080:8080"
    networks:
      - nightout-network

networks:
  nightout-network:
    driver: bridge

volumes:
  postgres-data: 