version: '3.8'

services:
  nightout-postgres:
    image: postgres:14
    container_name: nightout-postgres
    environment:
      POSTGRES_DB: nightoutdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nightout-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nightoutdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  nightout-backend:
    image: zachholt/nightout-backend:latest
    container_name: nightout-backend
    depends_on:
      nightout-postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nightout-postgres:5432/nightoutdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - nightout-network

  nginx:
    image: nginx:latest
    container_name: nightout-nginx
    depends_on:
      - nightout-backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - ./nginx/selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro
    networks:
      - nightout-network

networks:
  nightout-network:
    driver: bridge

volumes:
  postgres-data: 