spring:
  application:
    name: NightoutAPI
  datasource:
    url: jdbc:postgresql://postgres:5432/nightoutdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 8080