spring:
  application:
    name: NightoutAPI-Local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.community.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  codec:
    max-in-memory-size: 10MB

server:
  port: 8081  # Different from production port to avoid conflicts
  connection-timeout: 30s

# Swagger/OpenAPI configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: false
  packages-to-scan: com.zachholt.nightout.controllers

ai:
  api:
    url: http://localhost:8080/mock-ai  # Mock URL for local testing
    token: test_token

# Enable actuator endpoints for local development
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 