spring:
  application:
    name: NightoutAPI
  datasource:
    url: jdbc:h2:mem:nightoutdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

server:
  port: 8080