spring:
  application:
    name: NightoutAPI
  datasource:
    url: jdbc:postgresql://nightout-postgres:5432/nightoutdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      initialization-fail-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  codec:
    max-in-memory-size: 10MB

server:
  port: 8080

ai:
  api:
    url: https://lisa-rest-2067001295.us-east-1.elb.amazonaws.com
    token: test_token