name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build
        run: mvn clean install
      - name: Docker Login
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Docker Build
        run: |
          docker build -t zachholt/nightout-backend .

      - name: Push Image
        run: docker push zachholt/nightout-backend:latest



  deploy:
      needs:  build
      runs-on: [ec2-runner]
      steps:
        - name: Pull Docker Image
          run: |
            sudo docker pull zachholt/nightout-backend:latest
        - name: Remove Container
          run: |
            sudo docker rm -f nightout-backend
        - name: Run Docker Container
          run: |
            sudo docker run -d -p 8080:8080 --name nightout-backend zachholt/nightout-backend:latest